### ISSUE TITLE
共通パケットエンコーダ/デコーダに切り替える

### ISSUE THREAD

**Issue by KANAIHIROYUKI** [ibis-ssl/G474_Orion_main#16]
https://github.dev/ibis-ssl/crane/blob/multiple-control-mode/crane_sender/include/crane_sender/robot_packet.h
動くんじゃねぇかな･･･

**Comment by HansRobo** [comment]
動け動け動け

**Comment by KANAIHIROYUKI** [comment]
8716a616362ee0d8f7aa0a7b46aea0ccad33121d
動いたﾌｩ~
