### ISSUE TITLE
加速度制御の実装が必要最低限すぎてちゃんと加速度を制御できていない

### ISSUE THREAD

**Issue by ChikuwaRobo** [ibis-ssl/G474_Orion_main#7]
今の実装では、加速度の大部分がFF項で決定されている。これがよくない(とりあえず動いてはいるけど)

#### 具体的な実装
(実装上)加速度は2つ要素で決定される。1つめは、ロボット内で計算される目標速度の変化率。2つめは、モーターの出力トルク。
出力トルクについては、モーターの電圧比例した回転数にP追従するという特性を見込んだ実装になっている。
したがって、現在速度+一定電圧を加えると、その一定電圧ぶんのトルク(加速度)で目標速度に追従する、という動きになる。
しかし、その一定電圧ぶんが速度にPの比例項として扱われており(まずここが良くない)、目標速度の変化率とは別定義になっていたため、加速度パラメーターを変更しても、適切に反映されていなかった。

#### センサーの性能による加速度制御の制約
エンコーダーの性能があまり良くないため、速度を正確に制御するのはちょっと難しい。具体的には、内部の目標速度と、実際の速度の差分をとってフィードバックをできるほどの精度が出せない。
(但し、実用上、モーターの各加速度はたかが知れているので、エンコーダーのフィルタの時定数をもう少し大きくできるはずで、もう少し改善の余地はあるはず)

また、機体によって200kVモーターと300kVモーターの2種が混在しているため、後述の疑似電流制御モードの実装で問題になるかもしれない

#### どうするのか？
バグ修正：加速度の設定値によって、適切なトルク出力が可能になるようにする
制御全体の改善：疑似電流制御モードとかあってもいいかもしれない

**Comment by KANAIHIROYUKI** [comment]
いろいろいじっていて感じたが、加速度制御をもう少しまともにするのもよいが、その前にいくつかやるべきことがある
1. モーター単体でちゃんと回るようにする(モーターベンチを作ってちゃんと計測できる環境を作る)
2. 速度フィードバックをちゃんとできるようにする
3. データのグラフ化等を容易にする(CM4とマイコンの間の通信を安定させる)

**Comment by KANAIHIROYUKI** [comment]
位置ベースの速度制御とFF項目を組み合わせて、応答性と速度の精度をいくらかマシにした
https://github.com/ibis-ssl/G474_Orion_main/commit/1baf7dc85d2fc5c6cb5eaede168f11dee47ab3ff
加速時のFF項の変動の生協もあり、不安定になりがち。モーター単位の制御改善も含めて、全体的に調整は必要だがこの方向でとりあえずは良いともう

**Comment by ChikuwaRobo** [comment]
モーター単位の角度制御としたので解決した
